version: '3'

services:
  elastiflow-logstash:
    image: robcowart/elastiflow-logstash:4.0.1
    #container_name: elastiflow-logstash
    #restart: 'no'
    depends_on:
      - elastiflow-elasticsearch
    networks: 
      - elastiflow-net
      - traefik-public
    environment:
      # JVM Heap size - this MUST be at least 3GB (4GB preferred)
      LS_JAVA_OPTS: '-Xms4g -Xmx4g'

      # ElastiFlow global configuration
      ELASTIFLOW_AGENT_ID: elastiflow
      ELASTIFLOW_GEOIP_CACHE_SIZE: 16384
      ELASTIFLOW_GEOIP_LOOKUP: 'true'
      ELASTIFLOW_ASN_LOOKUP: 'true'
      ELASTIFLOW_OUI_LOOKUP: 'false'
      ELASTIFLOW_POPULATE_LOGS: 'true'
      ELASTIFLOW_KEEP_ORIG_DATA: 'true'
      ELASTIFLOW_DEFAULT_APPID_SRCTYPE: '__UNKNOWN'

      # Name resolution option
      ELASTIFLOW_RESOLVE_IP2HOST: 'false'
      ELASTIFLOW_NAMESERVER: '0.0.0.0'
      ELASTIFLOW_DNS_HIT_CACHE_SIZE: 25000
      ELASTIFLOW_DNS_HIT_CACHE_TTL: 900
      ELASTIFLOW_DNS_FAILED_CACHE_SIZE: 75000
      ELASTIFLOW_DNS_FAILED_CACHE_TTL: 3600

      ELASTIFLOW_ES_HOST: 'http://elastiflow-elasticsearch_elastiflow-elasticsearch:9200'
      ELASTIFLOW_ES_USER: 'elastic'
      ELASTIFLOW_ES_PASSWD: 'hahalolo@2020'

      ELASTIFLOW_NETFLOW_IPV4_PORT: 2055
      ELASTIFLOW_NETFLOW_UDP_WORKERS: 2
      ELASTIFLOW_NETFLOW_UDP_QUEUE_SIZE: 4096
      ELASTIFLOW_NETFLOW_UDP_RCV_BUFF: 33554432

      ELASTIFLOW_SFLOW_IPV4_PORT: 6343
      ELASTIFLOW_SFLOW_UDP_WORKERS: 2
      ELASTIFLOW_SFLOW_UDP_QUEUE_SIZE: 4096
      ELASTIFLOW_SFLOW_UDP_RCV_BUFF: 33554432

      ELASTIFLOW_IPFIX_UDP_IPV4_PORT: 4739
      ELASTIFLOW_IPFIX_UDP_WORKERS: 2
      ELASTIFLOW_IPFIX_UDP_QUEUE_SIZE: 4096
      ELASTIFLOW_IPFIX_UDP_RCV_BUFF: 33554432
 
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      #resources:
      #  limits:
      #    cpus: '2.0' # 50% of single CPU
      #    memory: 4G
      #restart_policy:
      #  condition: on-failure
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.docker.lbswarm=true
      - traefik.udp.routers.logstack.entrypoints=4739
      - traefik.constraint-label=traefik-public
      - traefik.udp.routers.logstack.service=logstack
      - traefik.udp.services.logstack.loadbalancer.server.port=4739
      - traefik.udp.routers.logtack.rule=Host(`elastiflow-logstack.hahalolo.com`)
      #  - traefik.udp.routers.logtack.entrypoints=udp
        #- traefik.http.routers.elastiflow-kibana-http.middlewares=https-redirect
        #- traefik.http.routers.elastiflow--kibana-https.rule=Host(`elastiflow-kibana.hahalolo.com`)
        #- traefik.http.routers.elastiflow-kibana-https.entrypoints=https
        #- traefik.http.routers.elastiflow-kibana-https.tls=true
        #- traefik.http.routers.elastiflow-kibana-https.middlewares=compress,security,cors
       # - traefik.udp.services.logtack.loadbalancer.server.port=2055
  
# ======================
#       NETWORK
# ======================
networks:
  traefik-public:
    external: true
  elastiflow-net:
    external: true